Blogz/Blogz.Web/Controllers/AdminBlogPostController.cs
using Blogz.Web.Models.Domain;
using Blogz.Web.Models.ViewModels;
using Blogz.Web.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
namespace Blogz.Web.Controllers
{
    [Authorize(Roles = "SuperAdmin,Admin")]
    public class AdminBlogPostController : Controller
    {
        private readonly ITagRepository tagRepository;
        private readonly IBlogPostRepository blogPostRepository;

        public AdminBlogPostController(ITagRepository tagRepository, IBlogPostRepository blogPostRepository)
        {
            this.tagRepository = tagRepository;
            this.blogPostRepository = blogPostRepository;
        }

        public IBlogPostRepository BlogPostRepository { get; }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var tags = await tagRepository.GetAllTagsAsync();

            var model = new AddBlogPostRequest
            {
                Tags = tags.Select(x => new SelectListItem { Text = x.DisplayName, Value = x.Id.ToString() })
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddBlogPostRequest request)
        {
            var tags = await tagRepository.GetAllTagsAsync();

            var blogPostrequest = new BlogPost
            {
                Heading = request.Heading,
                Author = request.Author,
                Content = request.Content,
                FeaturedImageUrl = request.FeaturedImageUrl,
                IsVisible = request.IsVisible,
                PageTitle = request.PageTitle,
                ShortDescription = request.ShortDescription,
                Tags = tags.Where(p => request.SelectedTags.Contains(p.Id.ToString())).ToList(), //in a real world situation, only loop through the selected tags
                UrlHandle = request.UrlHandle,
                PublishDate = request.PublishDate
            };

            var blogPost = await blogPostRepository.CreateAsync(blogPostrequest);

            return RedirectToAction("GetAllBlogPosts");
        }

        [HttpGet]
        public async Task<IActionResult> GetAllBlogPosts()
        {
            var blogPosts = await blogPostRepository.GetAllAsync();

            return View(blogPosts);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid blogId)
        {
            var blogpostResponse = await blogPostRepository.GetByIdAsync(blogId);

            var tags = await tagRepository.GetAllTagsAsync();

            if (blogpostResponse != null)
            {
                if (blogpostResponse != null)
                {
                    var blogPost = new EditBlogPostRequest
                    {
                        Id = blogpostResponse.Id,
                        Author = blogpostResponse.Author,
                        Heading = blogpostResponse.Heading,
                        Content = blogpostResponse.Content,
                        ShortDescription = blogpostResponse.ShortDescription,
                        PublishDate = blogpostResponse.PublishDate,
                        IsVisible = blogpostResponse.IsVisible,
                        FeaturedImageUrl = blogpostResponse.FeaturedImageUrl,
                        UrlHandle = blogpostResponse.UrlHandle,
                        PageTitle = blogpostResponse.PageTitle,
                        Tags = tags.Select(p => new SelectListItem { Value = p.Id.ToString(), Text = p.Name }),
                        SelectedTags = blogpostResponse.Tags.Select(p => p.Id.ToString()).ToArray(),
                    };

                    return View(blogPost);
                }
            }

            return View(null);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditBlogPostRequest request)
        {
            var tags = await tagRepository.GetAllTagsAsync();

            var blogPost = new BlogPost
            {
                Id = request.Id,
                Author = request.Author,
                Heading = request.Heading,
                Content = request.Content,
                ShortDescription = request.ShortDescription,
                PublishDate = request.PublishDate,
                IsVisible = request.IsVisible,
                FeaturedImageUrl = request.FeaturedImageUrl,
                UrlHandle = request.UrlHandle,
                PageTitle = request.PageTitle,
                Tags = tags.Where(p => request.SelectedTags.Contains(p.Id.ToString())).ToList(), //in a real world situation, only loop through the selected tags
            };

            var editTag = await blogPostRepository.EditAsync(blogPost);

            if (editTag != null)
            {
                return RedirectToAction("Edit", new { blogId = request.Id });
            }

            return RedirectToAction("Edit", new { blogId = request.Id });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(EditBlogPostRequest request)
        {
            var deleteResult = await blogPostRepository.DeleteAsync(request.Id);

            if (deleteResult != null)
            {
                return RedirectToAction("GetAllBlogPosts");
            }

            return RedirectToAction("Edit", new { blogId = request.Id });
        }
    }
}

Blogz/Blogz.Web/Controllers/AdminTagController.cs
using Blogz.Web.Models.Domain;
using Blogz.Web.Models.ViewModels;
using Blogz.Web.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Blogz.Web.Controllers
{
    [Authorize(Roles = "SuperAdmin,Admin")]
    public class AdminTagController : Controller
    {
        private readonly ITagRepository tagRepository;

        public AdminTagController(ITagRepository tagRepository)
        {
            this.tagRepository = tagRepository;
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(SaveTagRequest request)
        {
            ValidateAddTagRequest(request);

            if (!ModelState.IsValid)
            {
                return View();
            }

            var tag = new Tag
            {
                Name = request.Name,
                DisplayName = request.DisplayName
            };

            var addTag = await tagRepository.SaveTagAsync(tag);

            return RedirectToAction("GetTags");
        }

        [HttpGet]
        public async Task<IActionResult> GetTags(string? searchQuery, string? sortBy, string? sortDirection, int pageSize = 2, int pageNumber = 1)
        {
            ViewBag.SearchQuery = searchQuery;  
            ViewBag.SortBy = sortBy;
            ViewBag.SortDirection = sortDirection;

            var totalRecords = await tagRepository.TotalRecords();
            var totalPages = Math.Ceiling((decimal)totalRecords / pageSize);

            if(pageNumber > totalPages)
            {
                pageNumber--;
            }
            if(pageNumber <= 0)
            {
                pageNumber++;
            }

            ViewBag.PageNumber = pageNumber;
            ViewBag.PageSize = pageSize;    
            ViewBag.TotalPages = totalPages;

            var tags = await tagRepository.GetAllTagsAsync(searchQuery, sortBy, sortDirection, pageNumber, pageSize);

            return View(tags);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid tagId) // name should match asp-route-tagId "tagId"
        {
            //var tag = blogsDbContext.Tags.Find(tagId);

            var tag = await tagRepository.GetTagAsync(tagId);

            if (tag != null)
            {
                var editTag = new EditTagRequest
                {
                    Id = tag.Id,
                    DisplayName = tag.DisplayName,
                    Name = tag.Name
                };

                return View(editTag);
            }

            return View(null);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(EditTagRequest request)
        {
            var tag = new Tag
            {
                Id = request.Id,
                DisplayName = request.DisplayName,
                Name = request.Name
            };

            var updatedTag = await tagRepository.EditTagAsync(tag);

            if (updatedTag != null)
            {
                //show success 
                RedirectToAction("Edit", new { tagId = request.Id });

                // return RedirectToAction("GetTags"); can redirect to list 
            }
            //show failure
            return RedirectToAction("Edit", new { tagId = request.Id });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(EditTagRequest request)
        {
            var tag = await tagRepository.DeleteTagAsync(request.Id);

            if (tag != null)
            {
                //show success notification

                return RedirectToAction("GetTags");
            }

            //show failed notification
            return RedirectToAction("Edit", new { tagId = request.Id });
        }

        private void ValidateAddTagRequest(SaveTagRequest request)
        {
            if(request.Name is not null && request.DisplayName is not null)
            {
                if(request.Name == request.DisplayName)
                {
                    ModelState.AddModelError("DisplayName", "Name can't be the same as displayName");
                }
            }
        }
    }
}

Blogz/Blogz.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Blogz.Web.Models.Domain.Entities
@inject SignInManager<ApplicationUser> signInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Blogz.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Blogz.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href='https://cdn.jsdelivr.net/npm/froala-editor@latest/css/froala_editor.pkgd.min.css' rel='stylesheet' type='text/css' />
    <script type='text/javascript' src='https://cdn.jsdelivr.net/npm/froala-editor@latest/js/froala_editor.pkgd.min.js'></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Blogz.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Admin
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="AdminTag" asp-action="Add">Add New Tag</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="AdminTag" asp-action="GetTags">View Tags</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="AdminBlogPost" asp-action="Add">Add Blog Post</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="AdminBlogPost" asp-action="GetAllBlogPosts">View Blog Posts</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="AdminUsers" asp-action="List">Users</a></li>
                                </ul>
                            </li>
                        }
                    </ul>
                    <div class="d-flex align-items-center">
                        @if (signInManager.IsSignedIn(User))
                        {
                                    <div class="me-3 text-light" >
                                @User?.Identity?.Name
                                </div>
                                <a class="btn me-3 bg-light text-dark" asp-area="" asp-controller="Account" asp-action="LogOut">Log Out</a>
                        }
                        else
                        {
                                <a class="btn me-3 bg-light text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                                <a class="btn me-3 bg-light text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        }
                     </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Blogz.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>